services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./wait-for-postgres.sh db ./main
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      RUN_ADDRESS: ":8080"
      DATABASE_URI: "host=db user=avito password=password dbname=avito sslmode=disable"
      DB_PASSWORD: password
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: avito
      POSTGRES_USER: avito
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./dumps:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U avito -d avito"]
      interval: 5s
      timeout: 5s
      retries: 10
