APP_BINARY=avito

.PHONY: build run test test-unit lint tidy docker-up docker-down

build:
	mkdir -p bin
	go build -o bin/$(APP_BINARY) ./cmd/avito

run:
	go run ./cmd/avito

test:
	go test ./...

test-unit:
	go test ./... -short

lint:
	gofmt -w cmd internal
	go test ./...

tidy:
	go mod tidy

docker-up:
	docker compose up --build

docker-down:
	docker compose down -v